set_property PACKAGE_PIN W5 [get_ports clk_pre] 
set_property IOSTANDARD LVCMOS33 [get_ports clk_pre]


set_property PACKAGE_PIN U18 [get_ports reset] 
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset] 

set_property PACKAGE_PIN L1 [get_ports ERR1] 
set_property IOSTANDARD LVCMOS33 [get_ports ERR1]


set_property PACKAGE_PIN W4 [get_ports {disp_7seg[10]}] 
set_property PACKAGE_PIN V4 [get_ports {disp_7seg[9]}] 
set_property PACKAGE_PIN U4 [get_ports {disp_7seg[8]}] 
set_property PACKAGE_PIN U2 [get_ports {disp_7seg[7]}] 
set_property PACKAGE_PIN W7 [get_ports {disp_7seg[6]}] 
set_property PACKAGE_PIN W6 [get_ports {disp_7seg[5]}] 
set_property PACKAGE_PIN U8 [get_ports {disp_7seg[4]}] 
set_property PACKAGE_PIN V8 [get_ports {disp_7seg[3]}] 
set_property PACKAGE_PIN U5 [get_ports {disp_7seg[2]}] 
set_property PACKAGE_PIN V5 [get_ports {disp_7seg[1]}] 
set_property PACKAGE_PIN U7 [get_ports {disp_7seg[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[9]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[8]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {disp_7seg[10]}]